# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uuidy < Formula
  desc "A small CLI tool for working with UUIDs"
  homepage "https://github.com/legaard/uuidy"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legaard/uuidy/releases/download/v0.1.0/uuidy_Darwin_x86_64.tar.gz"
      sha256 "2b7d38c057dbc81f2d6d92ecb3643f22b5909a64ba955c48b8e884d225bacf2c"

      def install
        bin.install "uuidy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legaard/uuidy/releases/download/v0.1.0/uuidy_Darwin_arm64.tar.gz"
      sha256 "5c9947ddde98b5d8e5c7f2a61b9d6d3ecd415c5e5aef745b8e2bdff9a203b19c"

      def install
        bin.install "uuidy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legaard/uuidy/releases/download/v0.1.0/uuidy_Linux_x86_64.tar.gz"
        sha256 "64b51d62105faafd33031f5e664a70b7e3dd642311fa1658e002466e2349c276"

        def install
          bin.install "uuidy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legaard/uuidy/releases/download/v0.1.0/uuidy_Linux_arm64.tar.gz"
        sha256 "53b6b9e68d309e3aa2f517f3f2fb1701fb690458ed6b0b5cfebf5c53b70cf7d7"

        def install
          bin.install "uuidy"
        end
      end
    end
  end
end
