# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uuidy < Formula
  desc "A small CLI tool for working with UUIDs"
  homepage "https://github.com/legaard/uuidy"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legaard/uuidy/releases/download/v0.2.0/uuidy_Darwin_x86_64.tar.gz"
      sha256 "95fbcec8db0703bb079bc54aa7b1a100e08c6d33f45b30e77cc37edaa5cba4d7"

      def install
        bin.install "uuidy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legaard/uuidy/releases/download/v0.2.0/uuidy_Darwin_arm64.tar.gz"
      sha256 "8eda9075526ab9bdd398fff1a4d7feaa1737baa53946ae8fd9b41bc1edc8106d"

      def install
        bin.install "uuidy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legaard/uuidy/releases/download/v0.2.0/uuidy_Linux_x86_64.tar.gz"
        sha256 "2b124a8e448e3a1fc180c889ddabdea16f5a0fd6bca5cea81266ab4455684236"

        def install
          bin.install "uuidy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/legaard/uuidy/releases/download/v0.2.0/uuidy_Linux_arm64.tar.gz"
        sha256 "ae46bea519fb619a073d7b3a816e0e32758b3d30e974b8ff915517ddc98d553e"

        def install
          bin.install "uuidy"
        end
      end
    end
  end
end
